kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [security]
    admin_user     = root
    admin_password = xxxxxx

    [auth]
    disable_login_form   = false
    disable_signout_menu = true

    [auth.basic]
    enabled = true

    [auth.anonymous]
    enabled = true

    [log]
    mode  = console
    level = warn

    [paths]
    data         = /var/lib/grafana
    logs         = /var/log/grafana
    plugins      = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [server]

    [database]

    [remote_cache]

    [users]

    [auth.google]

    [auth.github]

    [auth.generic_oauth]

    [auth.ldap]
    enabled = true
    config_file = /etc/grafana/ldap.toml
    allow_sign_up = true
    
    [auth.proxy]

    [dataproxy]

    [analytics]

    [dashboards]

    [smtp]
      enabled = true
      host = relay.site.com:25
      user =
      # If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
      password =
      cert_file =
      key_file =
      skip_verify = true
      from_address = grafana@site.com
      from_name = Grafana
      ehlo_identity =

    [metrics]

    [metrics.graphite]

    [snapshots]

    [external_image_storage]

    [external_image_storage.s3]

    [external_image_storage.webdav]

    [external_image_storage.gcs]

    [external_image_storage.azure_blob]

    [alerting]

    [panels]

    [plugins]
    
    [plugin.piechart]
    path = /var/lib/grafana/plugins/grafana-piechart-panel