kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storageclass
  volumeMode: Filesystem
  capacity:
    storage: 5Gi